//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquitectosAlmacenes.WCFArquitectosAlmacenes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFArquitectosAlmacenes.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarCredencialesUsuarios", ReplyAction="http://tempuri.org/IService/ValidarCredencialesUsuariosResponse")]
        System.Data.DataSet ValidarCredencialesUsuarios(string Usuario, string Contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarCredencialesUsuarios", ReplyAction="http://tempuri.org/IService/ValidarCredencialesUsuariosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ValidarCredencialesUsuariosAsync(string Usuario, string Contrasenia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ArquitectosAlmacenes.WCFArquitectosAlmacenes.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ArquitectosAlmacenes.WCFArquitectosAlmacenes.IService>, ArquitectosAlmacenes.WCFArquitectosAlmacenes.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ValidarCredencialesUsuarios(string Usuario, string Contrasenia) {
            return base.Channel.ValidarCredencialesUsuarios(Usuario, Contrasenia);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ValidarCredencialesUsuariosAsync(string Usuario, string Contrasenia) {
            return base.Channel.ValidarCredencialesUsuariosAsync(Usuario, Contrasenia);
        }
    }
}
