-- INSERCION DE DATOS POR DEFECTO

GO
insert into Departamentos VALUES ('SV-AH','Ahuachapan')
insert into Departamentos VALUES ('SV-CA','Caba�as')
insert into Departamentos VALUES ('SV-CH','Chalatenango')
insert into Departamentos VALUES ('SV-CU','Cuscatl�n')
insert into Departamentos VALUES ('SV-LI','La Libertad')
insert into Departamentos VALUES ('SV-MO','Moraz�n')
insert into Departamentos VALUES ('SV-PA','La Paz')
insert into Departamentos VALUES ('SV-SA','Santa Ana')
insert into Departamentos VALUES ('SV-SM','San Miguel')
insert into Departamentos VALUES ('SV-SO','Sonsonate')
insert into Departamentos VALUES ('SV-SS','San Salvador')
insert into Departamentos VALUES ('SV-SV','San Vicente')
insert into Departamentos VALUES ('SV-UN','La Uni�n')
insert into Departamentos VALUES ('SV-US','Usulutan')
GO
insert into Municipios values (1,'Ahuachapan','SV-AH')
insert into Municipios values (2,'Apaneca','SV-AH')
insert into Municipios values (3,'Atiquizaya','SV-AH')
insert into Municipios values (4,'Concepci�n de Ataco','SV-AH')
insert into Municipios values (5,'El Refugio','SV-AH')
insert into Municipios values (6,'Guaymango','SV-AH')
insert into Municipios values (7,'Jujutla','SV-AH')
insert into Municipios values (8,'San Francisco Men�ndez','SV-AH')
insert into Municipios values (9,'San Lorenzo','SV-AH')
insert into Municipios values (10,'San Pedro Puxtla','SV-AH')
insert into Municipios values (11,'Tacuba','SV-AH')
insert into Municipios values (12,'Tur�n','SV-AH')
GO
insert into Municipios values (13,'Sensuntepeque','SV-CA')
insert into Municipios values (14,'Cinquera','SV-CA')
insert into Municipios values (15,'Dolores','SV-CA')
insert into Municipios values (16,'Guacotecti','SV-CA')
insert into Municipios values (17,'Ilobasco ','SV-CA')
insert into Municipios values (18,'Jutiapa','SV-CA')
insert into Municipios values (19,'San Isidro','SV-CA')
insert into Municipios values (20,'Tejutepeque','SV-CA')
insert into Municipios values (21,'Victoria','SV-CA')
GO
insert into Municipios values (22,'Chalatenango','SV-CH')
insert into Municipios values (23,'Agua Caliente','SV-CH')
insert into Municipios values (24,'Arcatao','SV-CH')
insert into Municipios values (25,'Azacualpa','SV-CH')
insert into Municipios values (26,'Cancasque','SV-CH')
insert into Municipios values (27,'Cital�','SV-CH')
insert into Municipios values (28,'Comalapa','SV-CH')
insert into Municipios values (29,'Concepci�n Quezaltepeque','SV-CH')
insert into Municipios values (30,'Dulce Nombre de Mar�a','SV-CH')
insert into Municipios values (31,'El Carrizal','SV-CH')
insert into Municipios values (32,'El Para�so','SV-CH')
insert into Municipios values (33,'La Laguna','SV-CH')
insert into Municipios values (34,'La Palma','SV-CH')
insert into Municipios values (35,'La Reina','SV-CH')
insert into Municipios values (36,'Las Flores','SV-CH')
insert into Municipios values (37,'Las Vueltas','SV-CH')
insert into Municipios values (38,'Nombre de Jes�s','SV-CH')
insert into Municipios values (39,'Nueva Concepci�n ','SV-CH')
insert into Municipios values (40,'Nueva Trinidad','SV-CH')
insert into Municipios values (41,'Ojos de Agua','SV-CH')
insert into Municipios values (42,'Potonico','SV-CH')
insert into Municipios values (43,'San Antonio de la Cruz','SV-CH')
insert into Municipios values (44,'San Antonio Los Ranchos','SV-CH')
insert into Municipios values (45,'San Fernando','SV-CH')
insert into Municipios values (46,'San Francisco Lempa','SV-CH')
insert into Municipios values (47,'San Francisco Moraz�n','SV-CH')
insert into Municipios values (48,'San Ignacio','SV-CH')
insert into Municipios values (49,'San Isidro Labrador','SV-CH')
insert into Municipios values (50,'San Luis del Carmen','SV-CH')
insert into Municipios values (51,'San Miguel de Mercedes','SV-CH')
insert into Municipios values (52,'Santa Rita','SV-CH')
insert into Municipios values (53,'San Rafael','SV-CH')
insert into Municipios values (54,'Tejutla','SV-CH')

GO
insert into Municipios values (55,'Cojutepeque','SV-CU')
insert into Municipios values (56,'Candelaria','SV-CU')
insert into Municipios values (57,'El Carmen','SV-CU')
insert into Municipios values (58,'El Rosario','SV-CU')
insert into Municipios values (59,'Monte San Juan','SV-CU')
insert into Municipios values (60,'Oratorio de Concepci�n','SV-CU')
insert into Municipios values (61,'San Bartolom� Perulap�a','SV-CU')
insert into Municipios values (62,'San Crist�bal','SV-CU')
insert into Municipios values (63,'San Jos� Guayabal','SV-CU')
insert into Municipios values (64,'San Pedro Perulap�n','SV-CU')
insert into Municipios values (65,'San Rafael Cedros','SV-CU')
insert into Municipios values (66,'San Ram�n','SV-CU')
insert into Municipios values (67,'Santa Cruz Analquito','SV-CU')
insert into Municipios values (68,'Santa Cruz Michapa','SV-CU')
insert into Municipios values (69,'Suchitoto','SV-CU')
insert into Municipios values (70,'Tenancingo','SV-CU')


GO
insert into Municipios values (71,'Santa Tecla','SV-LI')
insert into Municipios values (72,'Antiguo Cuscatl�n','SV-LI')
insert into Municipios values (73,'Chiltiup�n','SV-LI')
insert into Municipios values (74,'Ciudad Arce','SV-LI')
insert into Municipios values (75,'Colon','SV-LI')
insert into Municipios values (76,'Comasagua','SV-LI')
insert into Municipios values (77,'Huiz�car','SV-LI')
insert into Municipios values (78,'Jayaque','SV-LI')
insert into Municipios values (79,'Jicalapa','SV-LI')
insert into Municipios values (80,'La Libertad','SV-LI')
insert into Municipios values (81,'Nuevo Cuscatlan','SV-LI')
insert into Municipios values (82,'Quezaltepeque','SV-LI')
insert into Municipios values (83,'San Juan Opico','SV-LI')
insert into Municipios values (84,'Sacacoyo','SV-LI')
insert into Municipios values (85,'San Jos� Villanueva','SV-LI')
insert into Municipios values (86,'San Mat�as','SV-LI')
insert into Municipios values (87,'San Pablo Tacachico','SV-LI')
insert into Municipios values (88,'Talnique','SV-LI')
insert into Municipios values (89,'Tamanique','SV-LI')
insert into Municipios values (90,'Teotepeque','SV-LI')
insert into Municipios values (91,'Tepecoyo','SV-LI')
insert into Municipios values (92,'Zaragoza','SV-LI')

GO
insert into Municipios values (93,'Zacatecoluca','SV-PA')
insert into Municipios values (94,'Cuyultit�n','SV-PA')
insert into Municipios values (95,'El Rosario','SV-PA')
insert into Municipios values (96,'Jerusal�n','SV-PA')
insert into Municipios values (97,'Mercedes La Ceiba','SV-PA')
insert into Municipios values (98,'Olocuilta','SV-PA')
insert into Municipios values (99,'Para�so de Osorio','SV-PA')
insert into Municipios values (100,'San Antonio Masahuat','SV-PA')
insert into Municipios values (101,'San Emigdio','SV-PA')
insert into Municipios values (102,'San Francisco Chinameca','SV-PA')
insert into Municipios values (103,'San Pedro Masahuat','SV-PA')
insert into Municipios values (104,'San Juan Nonualco','SV-PA')
insert into Municipios values (105,'San Juan Talpa','SV-PA')
insert into Municipios values (106,'San Juan Tepezontes','SV-PA')
insert into Municipios values (107,'San Luis La Herradura','SV-PA')
insert into Municipios values (108,'San Luis Talpa','SV-PA')
insert into Municipios values (109,'San Miguel Tepezontes','SV-PA')
insert into Municipios values (110,'San Pedro Nonualco','SV-PA')
insert into Municipios values (111,'San Rafael Obrajuelo','SV-PA')
insert into Municipios values (112,'Santa Mar�a Ostuma','SV-PA')
insert into Municipios values (113,'Santiago Nonualco','SV-PA')
insert into Municipios values (114,'Tapalhuaca','SV-PA')
GO
insert into Municipios values (115,'La Uni�n','SV-UN')
insert into Municipios values (116,'Anamor�s','SV-UN')
insert into Municipios values (117,'Bol�var','SV-UN')
insert into Municipios values (118,'Concepci�n de Oriente','SV-UN')
insert into Municipios values (119,'Conchagua','SV-UN')
insert into Municipios values (120,'El Carmen','SV-UN')
insert into Municipios values (121,'El Sauce','SV-UN')
insert into Municipios values (122,'El Sauce','SV-UN')
insert into Municipios values (123,'Lislique','SV-UN')
insert into Municipios values (124,'Meanguera del Golfo','SV-UN')
insert into Municipios values (125,'Nueva Esparta','SV-UN')
insert into Municipios values (126,'Pasaquina','SV-UN')
insert into Municipios values (127,'Polor�s','SV-UN')
insert into Municipios values (128,'San Alejo','SV-UN')
insert into Municipios values (129,'San Jos�','SV-UN')
insert into Municipios values (130,'Santa Rosa de Lima','SV-UN')
insert into Municipios values (131,'Yayantique','SV-UN')
insert into Municipios values (132,'Yucuaiqu�n','SV-UN')

GO
insert into Municipios values (133,'San Francisco Gotera','SV-MO')
insert into Municipios values (134,'Arambala','SV-MO')
insert into Municipios values (135,'Cacaopera','SV-MO')
insert into Municipios values (136,'Chilanga','SV-MO')
insert into Municipios values (137,'Corinto','SV-MO')
insert into Municipios values (138,'Delicias de Concepci�n','SV-MO')
insert into Municipios values (139,'El Divisadero','SV-MO')
insert into Municipios values (140,'El Rosario','SV-MO')
insert into Municipios values (141,'Gualococti','SV-MO')
insert into Municipios values (142,'Gualococti','SV-MO')
insert into Municipios values (143,'Joateca','SV-MO')
insert into Municipios values (144,'Jocoaitique','SV-MO')
insert into Municipios values (145,'Jocoro','SV-MO')
insert into Municipios values (146,'Lolotiquillo','SV-MO')
insert into Municipios values (147,'Meanguera','SV-MO')
insert into Municipios values (148,'Osicala','SV-MO')
insert into Municipios values (149,'Perqu�n','SV-MO')
insert into Municipios values (150,'San Carlos','SV-MO')
insert into Municipios values (151,'San Fernando','SV-MO')
insert into Municipios values (152,'San Isidro','SV-MO')
insert into Municipios values (153,'San Sim�n','SV-MO')
insert into Municipios values (154,'Sensembra','SV-MO')
insert into Municipios values (155,'Sociedad','SV-MO')
insert into Municipios values (156,'Torola','SV-MO')
insert into Municipios values (157,'Yamabal','SV-MO')
insert into Municipios values (158,'Yoloaiqu�n','SV-MO')

GO
insert into Municipios values (159,'San Miguel','SV-SM')
insert into Municipios values (160,'Carolina','SV-SM')
insert into Municipios values (161,'Chapeltique','SV-SM')
insert into Municipios values (162,'Chinameca','SV-SM')
insert into Municipios values (163,'Chirilagua','SV-SM')
insert into Municipios values (164,'Ciudad Barrios','SV-SM')
insert into Municipios values (165,'Comacar�n','SV-SM')
insert into Municipios values (166,'El Tr�nsito','SV-SM')
insert into Municipios values (167,'Lolotique','SV-SM')
insert into Municipios values (168,'Moncagua','SV-SM')
insert into Municipios values (169,'Nueva Guadalupe','SV-SM')
insert into Municipios values (170,'Nuevo Ed�n de San Juan','SV-SM')
insert into Municipios values (171,'Quelepa','SV-SM')
insert into Municipios values (172,'San Antonio','SV-SM')
insert into Municipios values (173,'San Gerardo','SV-SM')
insert into Municipios values (174,'San Jorge','SV-SM')
insert into Municipios values (175,'San Luis de la Reina','SV-SM')
insert into Municipios values (176,'San Rafael Oriente','SV-SM')
insert into Municipios values (177,'Sesori','SV-SM')
insert into Municipios values (178,'Uluazapa','SV-SM')

GO
insert into Municipios values (179,'San Salvador','SV-SS')
insert into Municipios values (180,'Aguilares','SV-SS')
insert into Municipios values (181,'Apopa','SV-SS')
insert into Municipios values (182,'Ayutuxtepeque','SV-SS')
insert into Municipios values (183,'Ciudad Delgado','SV-SS')
insert into Municipios values (184,'Cuscatancingo','SV-SS')
insert into Municipios values (185,'El Paisnal','SV-SS')
insert into Municipios values (186,'Guazapa','SV-SS')
insert into Municipios values (187,'Ilopango','SV-SS')
insert into Municipios values (188,'Mejicanos','SV-SS')
insert into Municipios values (189,'Nejapa','SV-SS')
insert into Municipios values (190,'Panchimalco','SV-SS')
insert into Municipios values (191,'Panchimalco','SV-SS')
insert into Municipios values (192,'San Marcos','SV-SS')
insert into Municipios values (193,'San Mart�n','SV-SS')
insert into Municipios values (194,'Santiago Texacuangos','SV-SS')
insert into Municipios values (195,'Santo Tom�s','SV-SS')
insert into Municipios values (196,'Soyapango','SV-SS')
insert into Municipios values (197,'Tonacatepeque','SV-SS')

GO
insert into Municipios values (198,'San Vicente','SV-SV')
insert into Municipios values (199,'Apastepeque','SV-SV')
insert into Municipios values (200,'Guadalupe','SV-SV')
insert into Municipios values (201,'San Cayetano Istepeque','SV-SV')
insert into Municipios values (202,'San Esteban Catarina','SV-SV')
insert into Municipios values (203,'San Ildefonso','SV-SV')
insert into Municipios values (204,'San Lorenzo','SV-SV')
insert into Municipios values (205,'San Sebasti�n','SV-SV')
insert into Municipios values (206,'Santa Clara','SV-SV')
insert into Municipios values (207,'Santo Domingo','SV-SV')
insert into Municipios values (208,'Tecoluca','SV-SV')
insert into Municipios values (209,'Tepetit�n','SV-SV')
insert into Municipios values (210,'Verapaz','SV-SV')

GO
insert into Municipios values (211,'Santa Ana','SV-SA')
insert into Municipios values (212,'Candelaria de la Frontera','SV-SA')
insert into Municipios values (213,'Chalchuapa','SV-SA')
insert into Municipios values (214,'Coatepeque','SV-SA')
insert into Municipios values (215,'El Congo','SV-SA')
insert into Municipios values (216,'El Porvenir','SV-SA')
insert into Municipios values (217,'Masahuat','SV-SA')
insert into Municipios values (218,'Metap�n','SV-SA')
insert into Municipios values (219,'San Antonio Pajonal','SV-SA')
insert into Municipios values (220,'San Sebasti�n Salitrillo','SV-SA')
insert into Municipios values (221,'Santa Rosa Guachipil�n','SV-SA')
insert into Municipios values (222,'Santiago de la Frontera','SV-SA')
insert into Municipios values (223,'Texistepeque','SV-SA')

GO
insert into Municipios values (224,'Sonsonate','SV-SO')
insert into Municipios values (225,'Acajutla','SV-SO')
insert into Municipios values (226,'Armenia','SV-SO')
insert into Municipios values (227,'Caluco','SV-SO')
insert into Municipios values (228,'Cuisnahuat','SV-SO')
insert into Municipios values (229,'Izalco','SV-SO')
insert into Municipios values (230,'Juay�a','SV-SO')
insert into Municipios values (231,'Nahuizalco','SV-SO')
insert into Municipios values (232,'Nahulingo','SV-SO')
insert into Municipios values (233,'Salcoatit�n','SV-SO')
insert into Municipios values (234,'San Antonio del Monte','SV-SO')
insert into Municipios values (235,'San Juli�n','SV-SO')
insert into Municipios values (236,'Santa Catarina Masahuat','SV-SO')
insert into Municipios values (237,'Santa Isabel Ishuat�n','SV-SO')
insert into Municipios values (238,'Santo Domingo de Guzm�n','SV-SO')
insert into Municipios values (239,'Sonzacate','SV-SO')

GO
insert into Municipios values (240,'Usulutan','SV-US')
insert into Municipios values (241,'Alegr�a','SV-US')
insert into Municipios values (242,'Berl�n','SV-US')
insert into Municipios values (243,'California','SV-US')
insert into Municipios values (244,'Concepci�n Batres','SV-US')
insert into Municipios values (245,'El Triunfo','SV-US')
insert into Municipios values (246,'Ereguayqu�n','SV-US')
insert into Municipios values (247,'Estanzuelas','SV-US')
insert into Municipios values (248,'Jiquilisco','SV-US')
insert into Municipios values (249,'Jucuapa','SV-US')
insert into Municipios values (250,'Jucuar�n','SV-US')
insert into Municipios values (251,'Mercedes Uma�a','SV-US')
insert into Municipios values (252,'Nueva Granada','SV-US')
insert into Municipios values (253,'Ozatl�n','SV-US')
insert into Municipios values (254,'Puerto El Triunfo','SV-US')
insert into Municipios values (255,'San Agust�n','SV-US')
insert into Municipios values (256,'San Buenaventura','SV-US')
insert into Municipios values (257,'San Dionisio','SV-US')
insert into Municipios values (258,'San Francisco Javier','SV-US')
insert into Municipios values (259,'Santa Elena','SV-US')
insert into Municipios values (260,'Santa Mar�a','SV-US')
insert into Municipios values (261,'Santiago de Mar�a','SV-US')
insert into Municipios values (262,'Tecap�n','SV-US')

